import {Router} from "express";
import crypto from "crypto";
import multer from "multer";
import Stripe from "stripe";
import mongoose from "mongoose";
import cloudinary from "../config/cloudinary.js";
import Profile from "../models/Profile.js";
import Story from "../models/Story.js";
import AboutPage from "../models/AboutPage.js";

const router=Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:12}});
const storyUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:12}});
const aboutUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:13}});
const stripeReady=String(process.env.STRIPE_SECRET_KEY||"").startsWith("sk_")&&!String(process.env.STRIPE_SECRET_KEY).includes("placeholder")&&!String(process.env.STRIPE_SECRET_KEY).includes("temporary");
const stripe=stripeReady?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const digest=value=>crypto.createHash("sha256").update(String(value)).digest();
const same=(a,b)=>crypto.timingSafeEqual(digest(a),digest(b));
const requireAdmin=(req,res,next)=>req.session.tamaraAdmin?next():res.redirect("/richgirlielifetammy");
const send=(file,resourceType="image")=>new Promise((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:"tfem-hotties",resource_type:resourceType},(error,result)=>error?reject(error):resolve({url:result.secure_url,publicId:result.public_id}));stream.end(file.buffer)});
const cleanStatus=value=>value==="active"?"active":"draft";
const bodyData=body=>({name:body.name,email:body.email,phone:body.phone,city:body.city,state:body.state,bio:body.bio,nationality:body.nationality,height:body.height,weight:body.weight,eyeColor:body.eyeColor,hairColor:body.hairColor,measurements:body.measurements,age:Number(body.age),availableTo:body.availableTo,subscriptionStatus:cleanStatus(body.subscriptionStatus)});

router.get("/richgirlielifetammy",(req,res)=>req.session.tamaraAdmin?res.redirect("/richgirlielifetammy/admin"):res.render("admin-login",{error:null}));
router.post("/richgirlielifetammy/login",(req,res)=>{const configured=process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD;const email=String(req.body.email||"").trim().toLowerCase();if(!configured||!same(email,String(process.env.ADMIN_EMAIL).trim().toLowerCase())||!same(req.body.password||"",process.env.ADMIN_PASSWORD))return res.status(401).render("admin-login",{error:"That email or password is incorrect."});req.session.tamaraAdmin=true;res.redirect("/richgirlielifetammy/admin")});
router.post("/richgirlielifetammy/logout",requireAdmin,(req,res)=>{delete req.session.tamaraAdmin;res.redirect("/richgirlielifetammy")});

router.get("/richgirlielifetammy/admin",requireAdmin,async(req,res)=>{const [profiles,stories]=await Promise.all([Profile.find().sort({updatedAt:-1}).lean(),Story.find().sort({updatedAt:-1}).lean()]);let payments=[],stripeSummary={connected:false,activeSubscriptions:0,revenue:0,currency:"usd",error:null};if(stripe){try{const [invoices,subscriptions]=await Promise.all([stripe.invoices.list({limit:50}),stripe.subscriptions.list({status:"active",limit:100})]);const tfemPrice=process.env.STRIPE_PRICE_ID;const hasTfemPrice=item=>item?.price?.id===tfemPrice||item?.pricing?.price_details?.price===tfemPrice;const tfemInvoices=invoices.data.filter(invoice=>invoice.lines?.data?.some(hasTfemPrice));const tfemSubscriptions=subscriptions.data.filter(subscription=>subscription.items?.data?.some(hasTfemPrice));payments=tfemInvoices.map(invoice=>({id:invoice.id,email:invoice.customer_email||invoice.customer_name||"Tfem customer",amount:(invoice.amount_paid||0)/100,currency:String(invoice.currency||"usd").toUpperCase(),status:invoice.status,date:new Date(invoice.created*1000)}));stripeSummary={connected:true,activeSubscriptions:tfemSubscriptions.length,revenue:payments.filter(x=>x.status==="paid").reduce((sum,x)=>sum+x.amount,0),currency:payments[0]?.currency||"USD",error:null}}catch(error){stripeSummary.error="Stripe is connected, but its Tfem payment report could not be loaded."}}res.render("admin-dashboard",{profiles,stories,payments,stripeSummary})});
router.get("/richgirlielifetammy/profiles/new",requireAdmin,(req,res)=>res.render("admin-profile-form",{profile:null,error:null,action:"/richgirlielifetammy/profiles/new"}));
router.get("/richgirlielifetammy/profiles/:id/edit",requireAdmin,async(req,res)=>{const profile=await Profile.findById(req.params.id).lean();if(!profile)return res.status(404).render("error",{message:"Profile not found"});res.render("admin-profile-form",{profile,error:null,action:`/richgirlielifetammy/profiles/${profile._id}/edit`})});

router.post("/richgirlielifetammy/profiles/new",requireAdmin,upload.fields([{name:"coverPhoto",maxCount:1},{name:"photos",maxCount:10},{name:"video",maxCount:1}]),async(req,res)=>{try{if(Number(req.body.age)<18)throw new Error("Profiles must be for adults age 18 or older.");if((req.files?.coverPhoto?.length||0)+(req.files?.photos?.length||0)>10)throw new Error("A profile can contain no more than 10 photos.");const photos=[];if(req.files?.coverPhoto?.[0])photos.push(await send(req.files.coverPhoto[0]));for(const file of req.files?.photos||[])photos.push(await send(file));const video=req.files?.video?.[0]?await send(req.files.video[0],"video"):null;await Profile.create({...bodyData(req.body),owner:new mongoose.Types.ObjectId(),adminManaged:true,photos,video});res.redirect("/richgirlielifetammy/admin")}catch(error){console.error(error);res.status(400).render("admin-profile-form",{profile:{...req.body,photos:[]},error:error.message||"The profile could not be saved.",action:"/richgirlielifetammy/profiles/new"})}});
router.post("/richgirlielifetammy/profiles/:id/edit",requireAdmin,upload.fields([{name:"coverPhoto",maxCount:1},{name:"photos",maxCount:10},{name:"video",maxCount:1}]),async(req,res)=>{let profile;try{profile=await Profile.findById(req.params.id);if(!profile)return res.status(404).render("error",{message:"Profile not found"});if(Number(req.body.age)<18)throw new Error("Profiles must be for adults age 18 or older.");const removed=[req.body.removePhotos||[]].flat();let photos=profile.photos.filter(x=>!removed.includes(x.publicId));const incoming=(req.files?.coverPhoto?.length||0)+(req.files?.photos?.length||0);if(photos.length+incoming>10)throw new Error("A profile can contain no more than 10 photos.");for(const photo of profile.photos.filter(x=>removed.includes(x.publicId)))if(photo.publicId)await cloudinary.uploader.destroy(photo.publicId).catch(()=>{});if(req.files?.coverPhoto?.[0])photos.unshift(await send(req.files.coverPhoto[0]));for(const file of req.files?.photos||[])photos.push(await send(file));if(!req.files?.coverPhoto?.[0]&&req.body.featuredPhoto){const featuredIndex=photos.findIndex(photo=>photo.publicId===req.body.featuredPhoto);if(featuredIndex>0)photos.unshift(...photos.splice(featuredIndex,1))}let video=profile.video;if(req.files?.video?.[0]){if(video?.publicId)await cloudinary.uploader.destroy(video.publicId,{resource_type:"video"}).catch(()=>{});video=await send(req.files.video[0],"video")}Object.assign(profile,bodyData(req.body),{photos,video});await profile.save();res.redirect("/richgirlielifetammy/admin")}catch(error){console.error(error);res.status(400).render("admin-profile-form",{profile:profile?.toObject?.()||{...req.body,photos:[]},error:error.message||"The profile could not be saved.",action:`/richgirlielifetammy/profiles/${req.params.id}/edit`})}});
router.post("/richgirlielifetammy/profiles/:id/status",requireAdmin,async(req,res)=>{await Profile.findByIdAndUpdate(req.params.id,{subscriptionStatus:cleanStatus(req.body.status)});res.redirect("/richgirlielifetammy/admin")});

router.get("/richgirlielifetammy/about-me",requireAdmin,async(req,res)=>{const about=await AboutPage.findOne({singletonKey:"tamara"}).lean();res.render("admin-about-form",{about,error:null})});
router.post("/richgirlielifetammy/about-me",requireAdmin,aboutUpload.fields([{name:"mainImage",maxCount:1},{name:"gallery",maxCount:12}]),async(req,res)=>{let about;try{about=await AboutPage.findOne({singletonKey:"tamara"})||new AboutPage({singletonKey:"tamara",gallery:[]});const removed=[req.body.removeGallery||[]].flat();let gallery=(about.gallery||[]).filter(image=>!removed.includes(image.publicId));if(gallery.length+(req.files?.gallery?.length||0)>12)throw new Error("The About Me gallery can contain no more than 12 pictures.");for(const image of (about.gallery||[]).filter(x=>removed.includes(x.publicId)))if(image.publicId)await cloudinary.uploader.destroy(image.publicId).catch(()=>{});for(const file of req.files?.gallery||[])gallery.push(await send(file));let mainImage=about.mainImage;if(req.files?.mainImage?.[0]){if(mainImage?.publicId)await cloudinary.uploader.destroy(mainImage.publicId).catch(()=>{});mainImage=await send(req.files.mainImage[0])}about.pageTitle=req.body.pageTitle;about.displayName=req.body.displayName;about.tagline=req.body.tagline;about.bio=req.body.bio;about.contactHeading=req.body.contactHeading;about.contactText=req.body.contactText;about.contactEmail=String(req.body.contactEmail||"").trim().toLowerCase();about.mainImage=mainImage;about.gallery=gallery;await about.save();res.redirect("/richgirlielifetammy/admin")}catch(error){console.error(error);res.status(400).render("admin-about-form",{about:about?.toObject?.()||req.body,error:error.message||"The About Me page could not be saved."})}});

router.get("/richgirlielifetammy/stories/new",requireAdmin,(req,res)=>res.render("admin-story-form",{story:null,error:null,action:"/richgirlielifetammy/stories/new"}));
router.get("/richgirlielifetammy/stories/:id/edit",requireAdmin,async(req,res)=>{const story=await Story.findById(req.params.id).lean();if(!story)return res.status(404).render("error",{message:"Story not found"});res.render("admin-story-form",{story,error:null,action:`/richgirlielifetammy/stories/${story._id}/edit`})});
router.post("/richgirlielifetammy/stories/new",requireAdmin,storyUpload.array("images",12),async(req,res)=>{try{const images=[];for(const file of req.files||[])images.push(await send(file));await Story.create({title:req.body.title,excerpt:req.body.excerpt,body:req.body.body,images,status:req.body.status==="published"?"published":"draft"});res.redirect("/richgirlielifetammy/admin")}catch(error){console.error(error);res.status(400).render("admin-story-form",{story:{...req.body,images:[]},error:error.message||"The story could not be saved.",action:"/richgirlielifetammy/stories/new"})}});
router.post("/richgirlielifetammy/stories/:id/edit",requireAdmin,storyUpload.array("images",12),async(req,res)=>{let story;try{story=await Story.findById(req.params.id);if(!story)return res.status(404).render("error",{message:"Story not found"});const removed=[req.body.removeImages||[]].flat();for(const image of story.images.filter(x=>removed.includes(x.publicId)))if(image.publicId)await cloudinary.uploader.destroy(image.publicId).catch(()=>{});const images=story.images.filter(x=>!removed.includes(x.publicId));for(const file of req.files||[])images.push(await send(file));if(images.length>12)throw new Error("A story can contain no more than 12 images.");story.title=req.body.title;story.excerpt=req.body.excerpt;story.body=req.body.body;story.images=images;story.status=req.body.status==="published"?"published":"draft";await story.save();res.redirect("/richgirlielifetammy/admin")}catch(error){console.error(error);res.status(400).render("admin-story-form",{story:story?.toObject?.()||{...req.body,images:[]},error:error.message||"The story could not be saved.",action:`/richgirlielifetammy/stories/${req.params.id}/edit`})}});
router.post("/richgirlielifetammy/stories/:id/status",requireAdmin,async(req,res)=>{const status=req.body.status==="published"?"published":"draft";await Story.findByIdAndUpdate(req.params.id,{status,...(status==="published"?{publishedAt:new Date()}:{})});res.redirect("/richgirlielifetammy/admin")});

export default router;
