import {Router} from "express";import Profile from "../models/Profile.js";import {usLocations,allCities} from "../data/usLocations.js";import {demoCities,demoProfilesFor,findDemoProfile} from "../data/demoProfiles.js";import {tamara} from "../data/tamara.js";
const router=Router();
router.get("/",async(_,res)=>{const locations=await Profile.aggregate([{$match:{subscriptionStatus:"active"}},{$group:{_id:{state:"$state",city:"$city"},count:{$sum:1}}},{$sort:{"_id.state":1,"_id.city":1}}]);for(const demoCity of demoCities){const demos=demoProfilesFor(demoCity.city,demoCity.state);const existing=locations.find(x=>x._id.state.toLowerCase()===demoCity.state.toLowerCase()&&x._id.city.toLowerCase()===demoCity.city.toLowerCase());if(existing)existing.count+=demos.length;else locations.unshift({_id:{state:demoCity.state,city:demoCity.city},count:demos.length})}res.render("home",{locations,states:usLocations})});
router.get("/api/cities",async(req,res)=>{const q=String(req.query.q||"").trim().toLowerCase();if(q.length<2)return res.json([]);const directory=allCities.filter(x=>x.city.toLowerCase().includes(q)||x.state.toLowerCase().includes(q));const rows=await Profile.aggregate([{$match:{subscriptionStatus:"active",$or:[{city:{$regex:escape(q),$options:"i"}},{state:{$regex:escape(q),$options:"i"}}]}},{$group:{_id:{city:"$city",state:"$state"}}},{$limit:10}]);const merged=[...rows.map(x=>x._id),...directory];const seen=new Set();res.json(merged.filter(x=>{const key=`${x.city}|${x.state}`.toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,10))});
router.get("/about-tamara",(_,res)=>res.render("tamara-about",{tamara}));
router.get("/about-tamara/gallery",(_,res)=>res.render("tamara-gallery",{tamara}));
router.get("/about-tamara/stories",(_,res)=>res.render("tamara-stories",{tamara}));
router.get("/models/:state/:city",async(req,res)=>{const profiles=await Profile.find({subscriptionStatus:"active",state:new RegExp(`^${escape(req.params.state)}$`,`i`),city:new RegExp(`^${escape(req.params.city)}$`,`i`)}).sort({createdAt:-1}).lean();profiles.push(...demoProfilesFor(req.params.city,req.params.state));res.render("listings",{profiles,city:req.params.city,state:req.params.state,tamara})});
router.get("/hottie/:slug",async(req,res)=>{const profile=await Profile.findOne({slug:req.params.slug,subscriptionStatus:"active"}).lean()||findDemoProfile(req.params.slug);if(!profile)return res.status(404).render("error",{message:"This profile is unavailable."});res.render("profile",{profile})});
function escape(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
export default router;
