import {Router} from "express";import Profile from "../models/Profile.js";import Story from "../models/Story.js";import AboutPage from "../models/AboutPage.js";import {usLocations,allCities} from "../data/usLocations.js";import {getDemoProfiles,findDemoProfile} from "../data/demoProfiles.js";
const router=Router();
router.get("/",async(_,res)=>{const [locations,about]=await Promise.all([Profile.aggregate([{$match:{subscriptionStatus:"active"}},{$group:{_id:{state:"$state",city:"$city"},count:{$sum:1}}},{$sort:{"_id.state":1,"_id.city":1}}]),AboutPage.findOne({singletonKey:"tamara"}).lean()]);res.render("home",{locations,states:usLocations,about:about||{displayName:"Tamara",greetingMessage:"Hi, I’m Tamara! The creator of this site. Welcome to TG Hotties."}})});
router.get("/api/cities",async(req,res)=>{const q=String(req.query.q||"").trim().toLowerCase();if(q.length<2)return res.json([]);const directory=allCities.filter(x=>x.city.toLowerCase().includes(q)||x.state.toLowerCase().includes(q));const rows=await Profile.aggregate([{$match:{subscriptionStatus:"active",$or:[{city:{$regex:escape(q),$options:"i"}},{state:{$regex:escape(q),$options:"i"}}]}},{$group:{_id:{city:"$city",state:"$state"}}},{$limit:10}]);const merged=[...rows.map(x=>x._id),...directory];const seen=new Set();res.json(merged.filter(x=>{const key=`${x.city}|${x.state}`.toLowerCase();if(seen.has(key))return false;seen.add(key);return true}).slice(0,10))});
router.get("/stories",async(req,res)=>{const stories=await Story.find({status:"published"}).sort({publishedAt:-1,createdAt:-1}).lean();res.render("stories",{stories})});
router.get("/stories/:slug",async(req,res)=>{const story=await Story.findOne({slug:req.params.slug,status:"published"}).lean();if(!story)return res.status(404).render("error",{message:"This story is unavailable."});res.render("story",{story})});
router.get("/about-me",async(req,res)=>{const about=await AboutPage.findOne({singletonKey:"tamara"}).lean();res.render("about-me",{about:about||{pageTitle:"About Me",displayName:"Tamara",tagline:"My story is coming soon.",bio:"",contactHeading:"If you have any questions, contact me here:",contactText:"",contactEmail:"",gallery:[]}})});
router.get("/gallery",async(req,res)=>{const about=await AboutPage.findOne({singletonKey:"tamara"}).lean();const images=about?.gallery?.length?about.gallery:(about?.mainImage?.url?[about.mainImage]:[]);res.render("gallery-page",{about:about||{displayName:"Tamara"},images})});
router.get("/models/:state/:city",async(req,res)=>{const [profiles,about]=await Promise.all([Profile.find({subscriptionStatus:"active",state:new RegExp(`^${escape(req.params.state)}$`,`i`),city:new RegExp(`^${escape(req.params.city)}$`,`i`)}).sort({createdAt:-1}).lean(),AboutPage.findOne({singletonKey:"tamara"}).lean()]);profiles.push(...getDemoProfiles(req.params.state,req.params.city));res.render("listings",{profiles,city:req.params.city,state:req.params.state,about:about||{displayName:"Tamara",greetingMessage:"Hi, I’m Tamara! The creator of this site. Welcome to TG Hotties."}})});
router.get("/hottie/:slug",async(req,res)=>{const profile=await Profile.findOne({slug:req.params.slug,subscriptionStatus:"active"}).lean()||findDemoProfile(req.params.slug);if(!profile)return res.status(404).render("error",{message:"This profile is unavailable."});res.render("profile",{profile})});
function escape(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
export default router;
